/**
 * Exact keyword strings from emojiData.js → optional UI labels (RU / EN) over CLDR defaults.
 * Search uses CLDR (emojiCldrEnriched.json) + these overrides only for display when set.
 * @type {Record<string, { ru: string; en: string }>}
 */
export const EMOJI_PHRASE_OVERRIDE = {
  "grinning happy smile": { ru: "Широкая улыбка", en: "Grinning Face" },
  "smiley happy": { ru: "Счастливый смайлик", en: "Smiley Face" },
  "smile happy laugh": { ru: "Радостная улыбка", en: "Happy Face" },
  "grin beam teeth": { ru: "Широкая ухмылка", en: "Beaming Face" },
  "laughing satisfied": { ru: "Довольный смех", en: "Laughing Face" },
  "sweat smile awkward": { ru: "Неловкая улыбка", en: "Sweat Smile" },
  "rofl rolling laughing": { ru: "Катается со смеху", en: "ROFL" },
  "joy crying laughing tears": { ru: "Смех до слёз", en: "Tears of Joy" },
  "slightly smiling": { ru: "Лёгкая улыбка", en: "Slightly Smiling" },
  "upside down smile": { ru: "Перевёрнутая улыбка", en: "Upside-down Face" },
  "blush smile happy": { ru: "Смущённая улыбка", en: "Blushing Face" },
  "angel innocent halo": { ru: "Ангел", en: "Angel Face" },
  "love hearts face": { ru: "В любви", en: "Smiling with Hearts" },
  "heart eyes love": { ru: "Влюблённый взгляд", en: "Heart Eyes" },
  "star struck excited": { ru: "Звёздный восторг", en: "Star-Struck" },
  "kiss blowing heart": { ru: "Воздушный поцелуй", en: "Blowing Kiss" },
  "kissing closed eyes": { ru: "Целует с закрытыми глазами", en: "Kissing with Closed Eyes" },
  "smiling tear": { ru: "Улыбка сквозь слёзы", en: "Smiling with Tear" },
  "yummy delicious tongue": { ru: "Облизывается", en: "Yummy Face" },
  "tongue out playful": { ru: "Показывает язык", en: "Tongue Out" },
  "wink tongue crazy": { ru: "С языком и подмигиванием", en: "Winking Tongue" },
  "zany silly crazy": { ru: "Дурашливый", en: "Zany Face" },
  "squinting tongue": { ru: "Прищур и язык", en: "Squinting Tongue" },
  "money face rich": { ru: "С деньгами во рту", en: "Money Face" },
  "hugging hug": { ru: "Обнимает", en: "Hugging Face" },
  "hand over mouth giggle": { ru: "Хихикает", en: "Giggling" },
  "shushing quiet secret": { ru: "Тсс (тихо)", en: "Shushing Face" },
  "thinking hmm": { ru: "Думает", en: "Thinking Face" },
  "zipper mouth shut": { ru: "Рот на замке", en: "Zipper-Mouth" },
  "raised eyebrow skeptical": { ru: "Скептик", en: "Raised Eyebrow" },
  "neutral face": { ru: "Нейтральное лицо", en: "Neutral Face" },
  "dotted line face": { ru: "Невидимка", en: "Dotted Line Face" },
  "eye roll": { ru: "Закатывает глаза", en: "Face Rolling Eyes" },
  "grimacing awkward": { ru: "Гримаса", en: "Grimacing Face" },
  "exhaling sigh relief": { ru: "Выдох с облегчением", en: "Exhaling Face" },
  "lying pinocchio": { ru: "Лжец (Пиноккио)", en: "Lying Face" },
  "pensive sad": { ru: "Задумчивая грусть", en: "Pensive Face" },
  "sleepy tired": { ru: "Сонный", en: "Sleepy Face" },
  "sleeping zzz": { ru: "Спит", en: "Sleeping Face" },
  "mask sick": { ru: "В медицинской маске", en: "Medical Mask" },
  "thermometer sick fever": { ru: "С температурой", en: "Face with Thermometer" },
  "bandage hurt injured": { ru: "С повязкой", en: "Face with Head-Bandage" },
  "nauseated sick": { ru: "Тошнит", en: "Nauseated Face" },
  "vomiting sick": { ru: "Рвота", en: "Vomiting Face" },
  "hot sweating": { ru: "Жарко", en: "Hot Face" },
  "cold freezing": { ru: "Холодно", en: "Cold Face" },
  "woozy drunk dizzy": { ru: "Шаткость", en: "Woozy Face" },
  "dizzy spiral": { ru: "Голова кругом", en: "Dizzy Face" },
  "mind blown exploding head": { ru: "Взрыв мозга", en: "Exploding Head" },
  "cowboy hat": { ru: "Ковбой", en: "Cowboy Hat Face" },
  "party celebrating": { ru: "Вечеринка", en: "Partying Face" },
  "disguise nose glasses": { ru: "Маскировка", en: "Disguised Face" },
  "cool sunglasses": { ru: "Крутой в очках", en: "Smiling with Sunglasses" },
  "nerd glasses": { ru: "Ботаник", en: "Nerd Face" },
  "monocle detective": { ru: "С моноклем", en: "Face with Monocle" },
  "pleading puppy eyes": { ru: "Умоляющие глазки", en: "Pleading Face" },
  "holding back tears": { ru: "Сдерживает слёзы", en: "Holding Back Tears" },
  "loudly crying sobbing": { ru: "Громко рыдает", en: "Loudly Crying Face" },
  "screaming fear horror": { ru: "Крик ужаса", en: "Screaming in Fear" },
  "steam nose angry": { ru: "В ярости", en: "Face with Steam From Nose" },
  "swearing cursing": { ru: "Ругается", en: "Face with Symbols on Mouth" },
  "smiling devil horns": { ru: "Улыбающийся с рогами", en: "Smiling Face with Horns" },
  "angry devil": { ru: "Злой дьявол", en: "Angry Face with Horns" },
  "skull crossbones": { ru: "Череп и кости", en: "Skull and Crossbones" },
  "cat heart eyes love": { ru: "Кот с сердечками", en: "Smiling Cat with Heart-Eyes" },
  "cat joy tears": { ru: "Кот смеётся до слёз", en: "Cat with Tears of Joy" },
  "wave hello hi bye": { ru: "Машет рукой", en: "Waving Hand" },
  "raised hand stop high five": { ru: "Дай пять / стоп", en: "Raised Hand" },
  "hand fingers splayed": { ru: "Растопыренные пальцы", en: "Hand with Fingers Splayed" },
  "pinched fingers italian": { ru: "Итальянский жест", en: "Pinched Fingers" },
  "crossed fingers luck": { ru: "Скрещённые пальцы", en: "Crossed Fingers" },
  "hand with index and thumb crossed": { ru: "Сердечко пальцами", en: "Hand with Crossed Fingers" },
  "love you gesture": { ru: "Жест «я тебя люблю»", en: "Love-You Gesture" },
  "rock on metal horns": { ru: "Коза (рок)", en: "Sign of the Horns" },
  "call me hang loose": { ru: "Позвони мне (шака)", en: "Call Me Hand" },
  "thumbs up like good": { ru: "Палец вверх", en: "Thumbs Up" },
  "thumbs down dislike bad": { ru: "Палец вниз", en: "Thumbs Down" },
  "fist bump punch": { ru: "Кулак", en: "Oncoming Fist" },
  "clapping applause": { ru: "Аплодисменты", en: "Clapping Hands" },
  "raising hands celebration": { ru: "Ура (руки вверх)", en: "Raising Hands" },
  "heart hands": { ru: "Руки-сердечко", en: "Heart Hands" },
  "pray please thanks folded hands": { ru: "Пожалуйста / спасибо", en: "Folded Hands" },
  "muscle bicep strong": { ru: "Бицепс", en: "Flexed Biceps" },
  "anatomical heart": { ru: "Анатомическое сердце", en: "Anatomical Heart" },
  "see no evil monkey": { ru: "Ничего не вижу", en: "See-No-Evil Monkey" },
  "hear no evil monkey": { ru: "Ничего не слышу", en: "Hear-No-Evil Monkey" },
  "speak no evil monkey": { ru: "Ничего не скажу", en: "Speak-No-Evil Monkey" },
  "polar bear": { ru: "Полярный медведь", en: "Polar Bear" },
  "baby chick": { ru: "Цыплёнок", en: "Baby Chick" },
  "hatching chick": { ru: "Вылупляется", en: "Hatching Chick" },
  "front facing chick": { ru: "Цыплёнок анфас", en: "Front-Facing Chick" },
  "two hump camel": { ru: "Двугорбый верблюд", en: "Two-Hump Camel" },
  "water buffalo": { ru: "Буйвол", en: "Water Buffalo" },
  "guide dog": { ru: "Собака-поводырь", en: "Guide Dog" },
  "black cat": { ru: "Чёрный кот", en: "Black Cat" },
  "paw prints": { ru: "Следы лап", en: "Paw Prints" },
  "christmas tree": { ru: "Новогодняя ёлка", en: "Christmas Tree" },
  "evergreen tree": { ru: "Хвойное дерево", en: "Evergreen Tree" },
  "deciduous tree": { ru: "Лиственное дерево", en: "Deciduous Tree" },
  "palm tree": { ru: "Пальма", en: "Palm Tree" },
  "four leaf clover luck": { ru: "Клевер на удачу", en: "Four Leaf Clover" },
  "fallen leaf autumn": { ru: "Осенний лист", en: "Fallen Leaf" },
  "maple leaf canada": { ru: "Кленовый лист", en: "Maple Leaf" },
  "sun with face": { ru: "Солнце с лицом", en: "Sun with Face" },
  "full moon face": { ru: "Луна с лицом", en: "Full Moon with Face" },
  "green apple": { ru: "Зелёное яблоко", en: "Green Apple" },
  "red apple": { ru: "Красное яблоко", en: "Red Apple" },
  "french fries": { ru: "Картофель фри", en: "French Fries" },
  "hot dog": { ru: "Хот-дог", en: "Hot Dog" },
  "ice cream soft serve": { ru: "Мягкое мороженое", en: "Soft Ice Cream" },
  "birthday cake": { ru: "Праздничный торт", en: "Birthday Cake" },
  "clinking beer mugs cheers": { ru: "Кружки пива", en: "Clinking Beer Mugs" },
  "clinking glasses champagne toast": { ru: "Бокалы с шампанским", en: "Clinking Glasses" },
  "police car": { ru: "Полицейская машина", en: "Police Car" },
  "fire engine truck": { ru: "Пожарная машина", en: "Fire Engine" },
  "high speed train shinkansen": { ru: "Синкансен", en: "High-Speed Train" },
  "flying saucer ufo": { ru: "НЛО", en: "Flying Saucer" },
  "red heart love": { ru: "Красное сердце", en: "Red Heart" },
  "broken heart": { ru: "Разбитое сердце", en: "Broken Heart" },
  "check mark green done": { ru: "Галочка", en: "Check Mark" },
  "cross mark no wrong": { ru: "Крестик", en: "Cross Mark" },
  "mobile phone": { ru: "Смартфон", en: "Mobile Phone" },
  "desktop computer monitor": { ru: "Компьютер", en: "Desktop Computer" },
  "laptop computer": { ru: "Ноутбук", en: "Laptop" },
  "magnifying glass search left": { ru: "Лупа", en: "Magnifying Glass" },
  "credit card": { ru: "Кредитная карта", en: "Credit Card" },
  "hamburger burger": { ru: "Гамбургер", en: "Hamburger" },
};
