/**
 * Comprehensive Unicode emoji dataset organized by categories.
 * All emojis here are standard Unicode and pass Python `emoji.is_emoji()`.
 *
 * Structure:
 *   { id, icon, labelKey, emojis: [[emoji, "keyword1 keyword2"], ...] }
 *
 * Search is performed against the keywords string (case-insensitive).
 */

export const EMOJI_CATEGORIES = [
  {
    id: "smileys",
    icon: "😀",
    labelKey: "emojiCatSmileys",
    emojis: [
      ["😀", "grinning happy smile"],
      ["😃", "smiley happy"],
      ["😄", "smile happy laugh"],
      ["😁", "grin beam teeth"],
      ["😆", "laughing satisfied"],
      ["😅", "sweat smile awkward"],
      ["🤣", "rofl rolling laughing"],
      ["😂", "joy crying laughing tears"],
      ["🙂", "slightly smiling"],
      ["🙃", "upside down smile"],
      ["😉", "wink"],
      ["😊", "blush smile happy"],
      ["😇", "angel innocent halo"],
      ["🥰", "love hearts face"],
      ["😍", "heart eyes love"],
      ["🤩", "star struck excited"],
      ["😘", "kiss blowing heart"],
      ["😗", "kissing"],
      ["😚", "kissing closed eyes"],
      ["😙", "kissing smiling"],
      ["🥲", "smiling tear"],
      ["😋", "yummy delicious tongue"],
      ["😛", "tongue out playful"],
      ["😜", "wink tongue crazy"],
      ["🤪", "zany silly crazy"],
      ["😝", "squinting tongue"],
      ["🤑", "money face rich"],
      ["🤗", "hugging hug"],
      ["🤭", "hand over mouth giggle"],
      ["🤫", "shushing quiet secret"],
      ["🤔", "thinking hmm"],
      ["🫡", "salute saluting"],
      ["🤐", "zipper mouth shut"],
      ["🤨", "raised eyebrow skeptical"],
      ["😐", "neutral face"],
      ["😑", "expressionless"],
      ["😶", "no mouth silent"],
      ["🫥", "dotted line face"],
      ["😏", "smirk"],
      ["😒", "unamused"],
      ["🙄", "eye roll"],
      ["😬", "grimacing awkward"],
      ["😮‍💨", "exhaling sigh relief"],
      ["🤥", "lying pinocchio"],
      ["😌", "relieved content"],
      ["😔", "pensive sad"],
      ["😪", "sleepy tired"],
      ["🤤", "drooling"],
      ["😴", "sleeping zzz"],
      ["😷", "mask sick"],
      ["🤒", "thermometer sick fever"],
      ["🤕", "bandage hurt injured"],
      ["🤢", "nauseated sick"],
      ["🤮", "vomiting sick"],
      ["🥵", "hot sweating"],
      ["🥶", "cold freezing"],
      ["🥴", "woozy drunk dizzy"],
      ["😵", "dizzy"],
      ["😵‍💫", "dizzy spiral"],
      ["🤯", "mind blown exploding head"],
      ["🤠", "cowboy hat"],
      ["🥳", "party celebrating"],
      ["🥸", "disguise nose glasses"],
      ["😎", "cool sunglasses"],
      ["🤓", "nerd glasses"],
      ["🧐", "monocle detective"],
      ["😕", "confused"],
      ["🫤", "diagonal mouth"],
      ["😟", "worried"],
      ["🙁", "slightly frowning"],
      ["😮", "open mouth surprised"],
      ["😯", "hushed"],
      ["😲", "astonished shocked"],
      ["😳", "flushed embarrassed"],
      ["🥺", "pleading puppy eyes"],
      ["🥹", "holding back tears"],
      ["😦", "frowning open mouth"],
      ["😧", "anguished"],
      ["😨", "fearful scared"],
      ["😰", "anxious sweat"],
      ["😥", "sad relieved"],
      ["😢", "crying tear"],
      ["😭", "loudly crying sobbing"],
      ["😱", "screaming fear horror"],
      ["😖", "confounded"],
      ["😣", "persevering"],
      ["😞", "disappointed sad"],
      ["😓", "downcast sweat"],
      ["😩", "weary tired"],
      ["😫", "tired face"],
      ["🥱", "yawning bored"],
      ["😤", "steam nose angry"],
      ["😡", "pouting angry red"],
      ["😠", "angry"],
      ["🤬", "swearing cursing"],
      ["😈", "smiling devil horns"],
      ["👿", "angry devil"],
      ["💀", "skull dead"],
      ["☠️", "skull crossbones"],
      ["💩", "poop poo"],
      ["🤡", "clown"],
      ["👹", "ogre demon"],
      ["👺", "goblin tengu"],
      ["👻", "ghost boo"],
      ["👽", "alien ufo"],
      ["👾", "space invader pixel"],
      ["🤖", "robot bot"],
      ["😺", "cat smile"],
      ["😸", "cat grinning"],
      ["😹", "cat joy tears"],
      ["😻", "cat heart eyes love"],
      ["😼", "cat smirk"],
      ["😽", "cat kiss"],
      ["🙀", "cat scared weary"],
      ["😿", "cat crying"],
      ["😾", "cat pouting angry"],
      ["🫶", "heart hands love"],
    ],
  },
  {
    id: "people",
    icon: "👋",
    labelKey: "emojiCatPeople",
    emojis: [
      ["👋", "wave hello hi bye"],
      ["🤚", "raised back of hand"],
      ["🖐️", "hand fingers splayed"],
      ["✋", "raised hand stop high five"],
      ["🖖", "vulcan spock"],
      ["🫱", "rightwards hand"],
      ["🫲", "leftwards hand"],
      ["🫳", "palm down"],
      ["🫴", "palm up"],
      ["👌", "ok perfect"],
      ["🤌", "pinched fingers italian"],
      ["🤏", "pinching small tiny"],
      ["✌️", "victory peace"],
      ["🤞", "crossed fingers luck"],
      ["🫰", "hand with index and thumb crossed"],
      ["🤟", "love you gesture"],
      ["🤘", "rock on metal horns"],
      ["🤙", "call me hang loose"],
      ["👈", "pointing left"],
      ["👉", "pointing right"],
      ["👆", "pointing up"],
      ["🖕", "middle finger"],
      ["👇", "pointing down"],
      ["☝️", "index pointing up"],
      ["🫵", "pointing at viewer"],
      ["👍", "thumbs up like good"],
      ["👎", "thumbs down dislike bad"],
      ["✊", "fist raised"],
      ["👊", "fist bump punch"],
      ["🤛", "left facing fist"],
      ["🤜", "right facing fist"],
      ["👏", "clapping applause"],
      ["🙌", "raising hands celebration"],
      ["🫶", "heart hands"],
      ["👐", "open hands"],
      ["🤲", "palms up together"],
      ["🤝", "handshake deal"],
      ["🙏", "pray please thanks folded hands"],
      ["✍️", "writing"],
      ["💅", "nail polish"],
      ["🤳", "selfie"],
      ["💪", "muscle bicep strong"],
      ["🦾", "mechanical arm"],
      ["🦿", "mechanical leg"],
      ["🦵", "leg"],
      ["🦶", "foot"],
      ["👂", "ear listen"],
      ["👃", "nose smell"],
      ["🧠", "brain smart mind"],
      ["🫀", "anatomical heart"],
      ["🫁", "lungs"],
      ["🦷", "tooth dental"],
      ["🦴", "bone"],
      ["👀", "eyes looking"],
      ["👁️", "eye"],
      ["👅", "tongue"],
      ["👄", "mouth lips"],
      ["👶", "baby"],
      ["🧒", "child"],
      ["👦", "boy"],
      ["👧", "girl"],
      ["🧑", "person adult"],
      ["👱", "blond hair"],
      ["👨", "man"],
      ["🧔", "beard"],
      ["👩", "woman"],
      ["🧓", "older person"],
      ["👴", "old man grandpa"],
      ["👵", "old woman grandma"],
      ["🙍", "frowning person"],
      ["💁", "tipping hand info"],
      ["🙅", "no gesture crossing"],
      ["🙆", "ok gesture"],
      ["🙋", "raising hand volunteer"],
      ["🧏", "deaf person"],
      ["🙇", "bowing person"],
      ["🤦", "facepalm"],
      ["🤷", "shrug whatever"],
      ["👮", "police officer cop"],
      ["🕵️", "detective spy"],
      ["💂", "guard"],
      ["🥷", "ninja"],
      ["👷", "construction worker"],
      ["🫅", "person with crown"],
      ["🤴", "prince"],
      ["👸", "princess"],
      ["👳", "turban"],
      ["👲", "cap"],
      ["🧕", "headscarf hijab"],
      ["🤵", "tuxedo"],
      ["👰", "bride veil"],
      ["🦸", "superhero"],
      ["🦹", "supervillain"],
      ["🧙", "mage wizard"],
      ["🧚", "fairy"],
      ["🧛", "vampire"],
      ["🧜", "merperson"],
      ["🧝", "elf"],
      ["🧞", "genie"],
      ["🧟", "zombie"],
      ["🧌", "troll"],
      ["💆", "massage"],
      ["💇", "haircut"],
      ["🚶", "walking"],
      ["🧍", "standing"],
      ["🧎", "kneeling"],
      ["🏃", "running"],
      ["💃", "dancing woman"],
      ["🕺", "dancing man"],
      ["👯", "people bunny ears"],
      ["🧖", "sauna steam"],
      ["👫", "couple holding hands"],
      ["👬", "men holding hands"],
      ["👭", "women holding hands"],
      ["💏", "kiss couple"],
      ["💑", "couple with heart"],
      ["👪", "family"],
    ],
  },
  {
    id: "animals",
    icon: "🐻",
    labelKey: "emojiCatAnimals",
    emojis: [
      ["🐶", "dog puppy"],
      ["🐱", "cat kitten"],
      ["🐭", "mouse"],
      ["🐹", "hamster"],
      ["🐰", "rabbit bunny"],
      ["🦊", "fox"],
      ["🐻", "bear"],
      ["🐼", "panda"],
      ["🐻‍❄️", "polar bear"],
      ["🐨", "koala"],
      ["🐯", "tiger"],
      ["🦁", "lion"],
      ["🐮", "cow"],
      ["🐷", "pig"],
      ["🐸", "frog"],
      ["🐵", "monkey"],
      ["🙈", "see no evil monkey"],
      ["🙉", "hear no evil monkey"],
      ["🙊", "speak no evil monkey"],
      ["🐒", "monkey"],
      ["🐔", "chicken"],
      ["🐧", "penguin"],
      ["🐦", "bird"],
      ["🐤", "baby chick"],
      ["🐣", "hatching chick"],
      ["🐥", "front facing chick"],
      ["🦆", "duck"],
      ["🦅", "eagle"],
      ["🦉", "owl wise"],
      ["🦇", "bat"],
      ["🐺", "wolf"],
      ["🐗", "boar"],
      ["🐴", "horse"],
      ["🦄", "unicorn magic"],
      ["🐝", "bee honeybee"],
      ["🪱", "worm"],
      ["🐛", "bug"],
      ["🦋", "butterfly"],
      ["🐌", "snail"],
      ["🐞", "ladybug"],
      ["🐜", "ant"],
      ["🪰", "fly"],
      ["🪲", "beetle"],
      ["🪳", "cockroach"],
      ["🦟", "mosquito"],
      ["🦗", "cricket"],
      ["🕷️", "spider"],
      ["🕸️", "spider web"],
      ["🦂", "scorpion"],
      ["🐢", "turtle"],
      ["🐍", "snake"],
      ["🦎", "lizard"],
      ["🦖", "dinosaur trex"],
      ["🦕", "sauropod dino"],
      ["🐙", "octopus"],
      ["🦑", "squid"],
      ["🦐", "shrimp"],
      ["🦞", "lobster"],
      ["🦀", "crab"],
      ["🪸", "coral"],
      ["🐡", "blowfish"],
      ["🐠", "tropical fish"],
      ["🐟", "fish"],
      ["🐬", "dolphin"],
      ["🐳", "whale spouting"],
      ["🐋", "whale"],
      ["🦈", "shark"],
      ["🐊", "crocodile"],
      ["🐅", "tiger"],
      ["🐆", "leopard"],
      ["🦓", "zebra"],
      ["🦍", "gorilla"],
      ["🦧", "orangutan"],
      ["🐘", "elephant"],
      ["🦛", "hippo"],
      ["🦏", "rhino"],
      ["🐪", "camel"],
      ["🐫", "two hump camel"],
      ["🦒", "giraffe"],
      ["🦘", "kangaroo"],
      ["🦬", "bison"],
      ["🐃", "water buffalo"],
      ["🐂", "ox"],
      ["🐄", "cow"],
      ["🐎", "horse racing"],
      ["🐖", "pig"],
      ["🐏", "ram"],
      ["🐑", "sheep"],
      ["🦙", "llama alpaca"],
      ["🐐", "goat"],
      ["🦌", "deer"],
      ["🐕", "dog"],
      ["🐩", "poodle"],
      ["🦮", "guide dog"],
      ["🐈", "cat"],
      ["🐈‍⬛", "black cat"],
      ["🪶", "feather"],
      ["🐓", "rooster"],
      ["🦃", "turkey"],
      ["🦤", "dodo"],
      ["🦚", "peacock"],
      ["🦜", "parrot"],
      ["🦢", "swan"],
      ["🦩", "flamingo"],
      ["🕊️", "dove peace"],
      ["🐇", "rabbit"],
      ["🦝", "raccoon"],
      ["🦨", "skunk"],
      ["🦡", "badger"],
      ["🦫", "beaver"],
      ["🦦", "otter"],
      ["🦥", "sloth"],
      ["🐁", "mouse"],
      ["🐀", "rat"],
      ["🐿️", "chipmunk"],
      ["🦔", "hedgehog"],
      ["🐾", "paw prints"],
      ["🐉", "dragon"],
      ["🐲", "dragon face"],
      ["🌵", "cactus desert"],
      ["🎄", "christmas tree"],
      ["🌲", "evergreen tree"],
      ["🌳", "deciduous tree"],
      ["🌴", "palm tree"],
      ["🪵", "wood log"],
      ["🌱", "seedling sprout"],
      ["🌿", "herb leaf"],
      ["☘️", "shamrock"],
      ["🍀", "four leaf clover luck"],
      ["🎍", "bamboo"],
      ["🪴", "potted plant"],
      ["🎋", "tanabata"],
      ["🍃", "leaf fluttering wind"],
      ["🍂", "fallen leaf autumn"],
      ["🍁", "maple leaf canada"],
      ["🪺", "nest eggs"],
      ["🪹", "empty nest"],
      ["🍄", "mushroom"],
      ["🌾", "rice sheaf"],
      ["💐", "bouquet flowers"],
      ["🌷", "tulip"],
      ["🌹", "rose love"],
      ["🥀", "wilted flower"],
      ["🪻", "hyacinth"],
      ["🌺", "hibiscus"],
      ["🌸", "cherry blossom sakura"],
      ["🌼", "blossom flower"],
      ["🌻", "sunflower"],
      ["🌞", "sun with face"],
      ["🌝", "full moon face"],
      ["🌛", "first quarter moon face"],
      ["🌜", "last quarter moon face"],
      ["🌚", "new moon face"],
      ["🌕", "full moon"],
      ["🌖", "waning gibbous moon"],
      ["🌗", "last quarter moon"],
      ["🌘", "waning crescent moon"],
      ["🌑", "new moon"],
      ["🌒", "waxing crescent moon"],
      ["🌓", "first quarter moon"],
      ["🌔", "waxing gibbous moon"],
      ["🌙", "crescent moon night"],
      ["🌎", "earth americas globe"],
      ["🌍", "earth africa europe globe"],
      ["🌏", "earth asia globe"],
      ["🪐", "saturn planet ring"],
      ["💫", "dizzy star"],
      ["⭐", "star"],
      ["🌟", "glowing star"],
      ["✨", "sparkles magic"],
      ["⚡", "lightning zap electricity bolt"],
      ["☄️", "comet"],
      ["💥", "boom explosion"],
      ["🔥", "fire hot flame lit"],
      ["🌪️", "tornado"],
      ["🌈", "rainbow"],
      ["☀️", "sun sunny"],
      ["🌤️", "sun behind small cloud"],
      ["⛅", "sun behind cloud"],
      ["🌥️", "sun behind large cloud"],
      ["☁️", "cloud"],
      ["🌦️", "sun behind rain cloud"],
      ["🌧️", "rain cloud"],
      ["⛈️", "thunder cloud rain"],
      ["🌩️", "lightning cloud"],
      ["🌨️", "snow cloud"],
      ["❄️", "snowflake cold winter"],
      ["☃️", "snowman"],
      ["⛄", "snowman without snow"],
      ["🌬️", "wind blowing face"],
      ["💨", "dash wind"],
      ["💧", "droplet water"],
      ["💦", "sweat droplets splash"],
      ["🫧", "bubbles"],
      ["☔", "umbrella rain"],
      ["☂️", "umbrella"],
      ["🌊", "wave ocean water"],
    ],
  },
  {
    id: "food",
    icon: "🍔",
    labelKey: "emojiCatFood",
    emojis: [
      ["🍏", "green apple"],
      ["🍎", "red apple"],
      ["🍐", "pear"],
      ["🍊", "orange tangerine"],
      ["🍋", "lemon"],
      ["🍌", "banana"],
      ["🍉", "watermelon"],
      ["🍇", "grapes"],
      ["🍓", "strawberry"],
      ["🫐", "blueberries"],
      ["🍈", "melon"],
      ["🍒", "cherries"],
      ["🍑", "peach"],
      ["🥭", "mango"],
      ["🍍", "pineapple"],
      ["🥥", "coconut"],
      ["🥝", "kiwi"],
      ["🍅", "tomato"],
      ["🍆", "eggplant aubergine"],
      ["🥑", "avocado"],
      ["🫛", "pea pod"],
      ["🥦", "broccoli"],
      ["🥬", "leafy green"],
      ["🥒", "cucumber"],
      ["🌶️", "hot pepper chili"],
      ["🫑", "bell pepper"],
      ["🌽", "corn"],
      ["🥕", "carrot"],
      ["🫒", "olive"],
      ["🧄", "garlic"],
      ["🧅", "onion"],
      ["🥔", "potato"],
      ["🍠", "sweet potato"],
      ["🫘", "beans"],
      ["🥜", "peanuts"],
      ["🍞", "bread"],
      ["🥐", "croissant"],
      ["🥖", "baguette french bread"],
      ["🫓", "flatbread"],
      ["🥨", "pretzel"],
      ["🥯", "bagel"],
      ["🥞", "pancakes"],
      ["🧇", "waffle"],
      ["🧀", "cheese"],
      ["🍖", "meat bone"],
      ["🍗", "chicken leg drumstick"],
      ["🥩", "steak cut of meat"],
      ["🥓", "bacon"],
      ["🍔", "hamburger burger"],
      ["🍟", "french fries"],
      ["🍕", "pizza"],
      ["🌭", "hot dog"],
      ["🥪", "sandwich"],
      ["🌮", "taco"],
      ["🌯", "burrito"],
      ["🫔", "tamale"],
      ["🥙", "pita falafel"],
      ["🧆", "falafel"],
      ["🥚", "egg"],
      ["🍳", "cooking fried egg"],
      ["🥘", "shallow pan food"],
      ["🍲", "pot food stew"],
      ["🫕", "fondue"],
      ["🥣", "bowl spoon cereal"],
      ["🥗", "salad"],
      ["🍿", "popcorn movie"],
      ["🧈", "butter"],
      ["🧂", "salt"],
      ["🥫", "canned food"],
      ["🍱", "bento box japanese"],
      ["🍘", "rice cracker"],
      ["🍙", "rice ball onigiri"],
      ["🍚", "rice"],
      ["🍛", "curry rice"],
      ["🍜", "ramen noodles"],
      ["🍝", "spaghetti pasta"],
      ["🍣", "sushi"],
      ["🍤", "fried shrimp tempura"],
      ["🍥", "fish cake"],
      ["🥮", "moon cake"],
      ["🍡", "dango"],
      ["🥟", "dumpling"],
      ["🥠", "fortune cookie"],
      ["🥡", "takeout box"],
      ["🦪", "oyster"],
      ["🍦", "ice cream soft serve"],
      ["🍧", "shaved ice"],
      ["🍨", "ice cream"],
      ["🍩", "doughnut donut"],
      ["🍪", "cookie"],
      ["🎂", "birthday cake"],
      ["🍰", "cake shortcake"],
      ["🧁", "cupcake"],
      ["🥧", "pie"],
      ["🍫", "chocolate bar"],
      ["🍬", "candy sweet"],
      ["🍭", "lollipop"],
      ["🍮", "custard flan"],
      ["🍯", "honey pot"],
      ["🍼", "baby bottle milk"],
      ["🥛", "glass milk"],
      ["☕", "coffee hot beverage"],
      ["🫖", "teapot"],
      ["🍵", "tea green"],
      ["🍶", "sake"],
      ["🍾", "champagne bottle"],
      ["🍷", "wine glass"],
      ["🍸", "cocktail martini"],
      ["🍹", "tropical drink"],
      ["🍺", "beer mug"],
      ["🍻", "clinking beer mugs cheers"],
      ["🥂", "clinking glasses champagne toast"],
      ["🥃", "tumbler glass whiskey"],
      ["🫗", "pouring liquid"],
      ["🥤", "cup straw soda"],
      ["🧋", "bubble tea boba"],
      ["🧃", "juice box"],
      ["🧉", "mate"],
      ["🧊", "ice cube"],
      ["🥢", "chopsticks"],
      ["🍽️", "plate cutlery"],
      ["🍴", "fork knife"],
      ["🥄", "spoon"],
    ],
  },
  {
    id: "travel",
    icon: "✈️",
    labelKey: "emojiCatTravel",
    emojis: [
      ["🚗", "car automobile"],
      ["🚕", "taxi cab"],
      ["🚙", "suv sport utility"],
      ["🚌", "bus"],
      ["🚎", "trolleybus"],
      ["🏎️", "racing car formula"],
      ["🚓", "police car"],
      ["🚑", "ambulance"],
      ["🚒", "fire engine truck"],
      ["🚐", "minibus van"],
      ["🛻", "pickup truck"],
      ["🚚", "delivery truck"],
      ["🚛", "articulated lorry"],
      ["🚜", "tractor farm"],
      ["🛵", "scooter motor"],
      ["🏍️", "motorcycle"],
      ["🛺", "auto rickshaw"],
      ["🚲", "bicycle bike"],
      ["🛴", "kick scooter"],
      ["🛹", "skateboard"],
      ["🛼", "roller skate"],
      ["🚏", "bus stop"],
      ["🛣️", "motorway highway road"],
      ["🚡", "aerial tramway"],
      ["🚠", "mountain cableway"],
      ["🚟", "suspension railway"],
      ["🚃", "railway car train"],
      ["🚋", "tram streetcar"],
      ["🚞", "mountain railway"],
      ["🚝", "monorail"],
      ["🚄", "high speed train shinkansen"],
      ["🚅", "bullet train"],
      ["🚈", "light rail"],
      ["🚂", "locomotive steam train"],
      ["🚆", "train"],
      ["🚇", "metro subway"],
      ["🚊", "tram"],
      ["🚉", "station"],
      ["✈️", "airplane plane flight"],
      ["🛫", "departure airplane takeoff"],
      ["🛬", "arrival airplane landing"],
      ["🛩️", "small airplane"],
      ["💺", "seat airplane"],
      ["🛰️", "satellite orbit space"],
      ["🚀", "rocket launch space"],
      ["🛸", "flying saucer ufo"],
      ["🚁", "helicopter"],
      ["🛶", "canoe boat"],
      ["⛵", "sailboat"],
      ["🚤", "speedboat"],
      ["🛥️", "motor boat"],
      ["🛳️", "passenger ship cruise"],
      ["⛴️", "ferry"],
      ["🚢", "ship boat"],
      ["⚓", "anchor"],
      ["🪝", "hook"],
      ["⛽", "fuel pump gas"],
      ["🚧", "construction"],
      ["🚦", "traffic light vertical"],
      ["🚥", "traffic light horizontal"],
      ["🗺️", "world map"],
      ["🗿", "moai easter island"],
      ["🗽", "statue of liberty"],
      ["🗼", "tokyo tower"],
      ["🏰", "castle european"],
      ["🏯", "castle japanese"],
      ["🏟️", "stadium"],
      ["🎡", "ferris wheel"],
      ["🎢", "roller coaster"],
      ["🎠", "carousel horse"],
      ["⛲", "fountain"],
      ["⛱️", "umbrella ground beach"],
      ["🏖️", "beach umbrella"],
      ["🏝️", "desert island"],
      ["🏜️", "desert"],
      ["🌋", "volcano"],
      ["⛰️", "mountain"],
      ["🏔️", "snow capped mountain"],
      ["🗻", "mount fuji"],
      ["🏕️", "camping tent"],
      ["⛺", "tent"],
      ["🏠", "house"],
      ["🏡", "house garden"],
      ["🏢", "office building"],
      ["🏣", "post office japanese"],
      ["🏥", "hospital"],
      ["🏦", "bank"],
      ["🏨", "hotel"],
      ["🏩", "love hotel"],
      ["🏪", "convenience store"],
      ["🏫", "school"],
      ["🏬", "department store"],
      ["🏭", "factory"],
      ["🕌", "mosque"],
      ["🛕", "hindu temple"],
      ["🕍", "synagogue"],
      ["⛩️", "shinto shrine"],
      ["🕋", "kaaba"],
      ["⛪", "church"],
      ["🌃", "night city stars"],
      ["🌆", "cityscape dusk"],
      ["🌇", "sunset"],
      ["🌅", "sunrise"],
      ["🌄", "sunrise over mountains"],
      ["🌉", "bridge at night"],
      ["🎆", "fireworks"],
      ["🎇", "sparkler"],
      ["🏙️", "cityscape"],
    ],
  },
  {
    id: "activities",
    icon: "⚽",
    labelKey: "emojiCatActivities",
    emojis: [
      ["⚽", "soccer football"],
      ["🏀", "basketball"],
      ["🏈", "football american"],
      ["⚾", "baseball"],
      ["🥎", "softball"],
      ["🎾", "tennis"],
      ["🏐", "volleyball"],
      ["🏉", "rugby"],
      ["🥏", "flying disc frisbee"],
      ["🎱", "pool billiards 8ball"],
      ["🪀", "yo-yo"],
      ["🏓", "ping pong table tennis"],
      ["🏸", "badminton"],
      ["🏒", "ice hockey"],
      ["🏑", "field hockey"],
      ["🥍", "lacrosse"],
      ["🏏", "cricket game"],
      ["🪃", "boomerang"],
      ["🥅", "goal net"],
      ["⛳", "golf flag hole"],
      ["🪁", "kite"],
      ["🏹", "bow arrow archery"],
      ["🎣", "fishing pole"],
      ["🤿", "diving mask"],
      ["🥊", "boxing glove"],
      ["🥋", "martial arts uniform"],
      ["🎽", "running shirt"],
      ["🛹", "skateboard"],
      ["🛼", "roller skate"],
      ["🛷", "sled"],
      ["⛸️", "ice skate"],
      ["🥌", "curling stone"],
      ["🎿", "ski skiing"],
      ["⛷️", "skier"],
      ["🏂", "snowboarder"],
      ["🪂", "parachute"],
      ["🏋️", "weight lifting"],
      ["🤼", "wrestling"],
      ["🤸", "cartwheeling gymnastics"],
      ["🤺", "fencing person"],
      ["⛹️", "basketball person"],
      ["🤾", "handball person"],
      ["🏊", "swimming person pool"],
      ["🚣", "rowing person boat"],
      ["🧗", "climbing person rock"],
      ["🚴", "bicycling person"],
      ["🚵", "mountain biking"],
      ["🏇", "horse racing"],
      ["🏆", "trophy winner champion"],
      ["🥇", "gold medal first"],
      ["🥈", "silver medal second"],
      ["🥉", "bronze medal third"],
      ["🏅", "sports medal"],
      ["🎖️", "military medal"],
      ["🎗️", "reminder ribbon"],
      ["🎪", "circus tent"],
      ["🤹", "juggling person"],
      ["🎭", "performing arts theater masks"],
      ["🩰", "ballet shoes"],
      ["🎨", "art palette paint"],
      ["🎬", "clapper board movie film"],
      ["🎤", "microphone karaoke singing"],
      ["🎧", "headphone music"],
      ["🎼", "musical score notes"],
      ["🎹", "musical keyboard piano"],
      ["🥁", "drum"],
      ["🪘", "long drum"],
      ["🎷", "saxophone"],
      ["🎺", "trumpet"],
      ["🪗", "accordion"],
      ["🎸", "guitar"],
      ["🪕", "banjo"],
      ["🎻", "violin"],
      ["🪈", "flute"],
      ["🎲", "game die dice"],
      ["♟️", "chess pawn"],
      ["🎯", "bullseye target dart"],
      ["🎳", "bowling"],
      ["🎮", "video game controller joystick"],
      ["🕹️", "joystick gaming retro"],
      ["🧩", "puzzle piece jigsaw"],
      ["🪩", "mirror ball disco"],
    ],
  },
  {
    id: "objects",
    icon: "💡",
    labelKey: "emojiCatObjects",
    emojis: [
      ["⌚", "watch time"],
      ["📱", "smartphone mobile phone"],
      ["📲", "mobile phone arrow"],
      ["💻", "laptop computer"],
      ["⌨️", "keyboard"],
      ["🖥️", "desktop computer monitor"],
      ["🖨️", "printer"],
      ["🖱️", "computer mouse"],
      ["🖲️", "trackball"],
      ["💽", "minidisc"],
      ["💾", "floppy disk save"],
      ["💿", "cd optical disk"],
      ["📀", "dvd"],
      ["🧮", "abacus"],
      ["🎥", "movie camera film"],
      ["🎞️", "film frames"],
      ["📽️", "film projector"],
      ["📺", "television tv"],
      ["📷", "camera photo"],
      ["📸", "camera flash"],
      ["📹", "video camera"],
      ["📼", "videocassette vhs"],
      ["🔍", "magnifying glass search left"],
      ["🔎", "magnifying glass search right"],
      ["🕯️", "candle"],
      ["💡", "light bulb idea"],
      ["🔦", "flashlight"],
      ["🏮", "red lantern"],
      ["🪔", "diya lamp"],
      ["📔", "notebook"],
      ["📕", "book closed red"],
      ["📖", "book open"],
      ["📗", "book green"],
      ["📘", "book blue"],
      ["📙", "book orange"],
      ["📚", "books stack"],
      ["📓", "notebook"],
      ["📒", "ledger"],
      ["📃", "page curl"],
      ["📜", "scroll"],
      ["📄", "page facing up document"],
      ["📰", "newspaper"],
      ["🗞️", "rolled up newspaper"],
      ["📑", "bookmark tabs"],
      ["🔖", "bookmark"],
      ["🏷️", "label tag"],
      ["💰", "money bag"],
      ["🪙", "coin"],
      ["💴", "yen banknote"],
      ["💵", "dollar banknote money"],
      ["💶", "euro banknote"],
      ["💷", "pound banknote"],
      ["💸", "money with wings"],
      ["💳", "credit card"],
      ["🧾", "receipt"],
      ["💹", "chart increasing yen"],
      ["✉️", "envelope mail letter"],
      ["📧", "email e-mail"],
      ["📨", "incoming envelope"],
      ["📩", "envelope arrow"],
      ["📤", "outbox tray"],
      ["📥", "inbox tray"],
      ["📦", "package box"],
      ["📫", "mailbox closed flag up"],
      ["📪", "mailbox closed flag down"],
      ["📬", "mailbox open flag up"],
      ["📭", "mailbox open flag down"],
      ["🗳️", "ballot box"],
      ["✏️", "pencil"],
      ["✒️", "black nib pen"],
      ["🖋️", "fountain pen"],
      ["🖊️", "pen"],
      ["🖌️", "paintbrush art"],
      ["🖍️", "crayon"],
      ["📝", "memo note writing"],
      ["📁", "file folder"],
      ["📂", "open file folder"],
      ["🗂️", "card index dividers"],
      ["📅", "calendar date"],
      ["📆", "tear off calendar"],
      ["🗒️", "spiral notepad"],
      ["🗓️", "spiral calendar"],
      ["📇", "card index"],
      ["📈", "chart increasing trending up"],
      ["📉", "chart decreasing trending down"],
      ["📊", "bar chart statistics"],
      ["📋", "clipboard"],
      ["📌", "pushpin pin"],
      ["📍", "round pushpin location"],
      ["📎", "paperclip"],
      ["🖇️", "linked paperclips"],
      ["📏", "straight ruler"],
      ["📐", "triangular ruler"],
      ["✂️", "scissors cut"],
      ["🗃️", "card file box"],
      ["🗄️", "file cabinet"],
      ["🗑️", "wastebasket trash delete"],
      ["🔒", "locked"],
      ["🔓", "unlocked"],
      ["🔏", "locked with pen"],
      ["🔐", "locked with key"],
      ["🔑", "key"],
      ["🗝️", "old key"],
      ["🔨", "hammer tool"],
      ["🪓", "axe"],
      ["⛏️", "pick"],
      ["⚒️", "hammer pick"],
      ["🛠️", "hammer wrench tools"],
      ["🗡️", "dagger"],
      ["⚔️", "crossed swords"],
      ["💣", "bomb"],
      ["🪃", "boomerang"],
      ["🏹", "bow arrow"],
      ["🛡️", "shield"],
      ["🪚", "carpentry saw"],
      ["🔧", "wrench"],
      ["🪛", "screwdriver"],
      ["🔩", "nut bolt"],
      ["⚙️", "gear settings cog"],
      ["🗜️", "clamp"],
      ["⚖️", "balance scale justice"],
      ["🦯", "white cane"],
      ["🔗", "link chain"],
      ["⛓️", "chains"],
      ["🪝", "hook"],
      ["🧰", "toolbox"],
      ["🧲", "magnet"],
      ["🪜", "ladder"],
      ["⚗️", "alembic chemistry"],
      ["🧪", "test tube"],
      ["🧫", "petri dish"],
      ["🧬", "dna"],
      ["🔬", "microscope science"],
      ["🔭", "telescope"],
      ["📡", "satellite antenna"],
      ["💉", "syringe"],
      ["🩸", "drop blood"],
      ["💊", "pill medicine"],
      ["🩹", "adhesive bandage"],
      ["🩼", "crutch"],
      ["🩺", "stethoscope doctor"],
      ["🩻", "x-ray"],
      ["🚪", "door"],
      ["🛗", "elevator"],
      ["🪞", "mirror"],
      ["🪟", "window"],
      ["🛏️", "bed"],
      ["🛋️", "couch lamp"],
      ["🪑", "chair seat"],
      ["🚽", "toilet"],
      ["🪠", "plunger"],
      ["🚿", "shower"],
      ["🛁", "bathtub"],
      ["🪤", "mouse trap"],
      ["🪒", "razor"],
      ["🧴", "lotion bottle"],
      ["🧷", "safety pin"],
      ["🧹", "broom"],
      ["🧺", "basket"],
      ["🧻", "roll paper toilet"],
      ["🪣", "bucket"],
      ["🧼", "soap"],
      ["🫧", "bubbles"],
      ["🪥", "toothbrush"],
      ["🧽", "sponge"],
      ["🧯", "fire extinguisher"],
      ["🛒", "shopping cart"],
      ["🚬", "cigarette smoking"],
      ["⚰️", "coffin"],
      ["🪦", "headstone"],
      ["⚱️", "funeral urn"],
      ["🧿", "nazar amulet evil eye"],
      ["🪬", "hamsa"],
      ["🗿", "moai"],
      ["🪧", "placard sign"],
      ["🪪", "identification card id"],
    ],
  },
  {
    id: "symbols",
    icon: "❤️",
    labelKey: "emojiCatSymbols",
    emojis: [
      ["❤️", "red heart love"],
      ["🧡", "orange heart"],
      ["💛", "yellow heart"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["💜", "purple heart"],
      ["🖤", "black heart"],
      ["🤍", "white heart"],
      ["🤎", "brown heart"],
      ["💔", "broken heart"],
      ["❤️‍🔥", "heart on fire"],
      ["❤️‍🩹", "mending heart"],
      ["❣️", "heart exclamation"],
      ["💕", "two hearts"],
      ["💞", "revolving hearts"],
      ["💓", "beating heart"],
      ["💗", "growing heart"],
      ["💖", "sparkling heart"],
      ["💘", "heart with arrow cupid"],
      ["💝", "heart ribbon gift"],
      ["💟", "heart decoration"],
      ["☮️", "peace symbol"],
      ["✝️", "latin cross"],
      ["☪️", "star crescent"],
      ["🕉️", "om"],
      ["☸️", "wheel dharma"],
      ["✡️", "star david"],
      ["🔯", "six pointed star"],
      ["🕎", "menorah"],
      ["☯️", "yin yang"],
      ["☦️", "orthodox cross"],
      ["🛐", "place worship"],
      ["⛎", "ophiuchus"],
      ["♈", "aries"],
      ["♉", "taurus"],
      ["♊", "gemini"],
      ["♋", "cancer"],
      ["♌", "leo"],
      ["♍", "virgo"],
      ["♎", "libra"],
      ["♏", "scorpio"],
      ["♐", "sagittarius"],
      ["♑", "capricorn"],
      ["♒", "aquarius"],
      ["♓", "pisces"],
      ["🆔", "id identification"],
      ["⚛️", "atom symbol"],
      ["🉑", "accept"],
      ["☢️", "radioactive"],
      ["☣️", "biohazard"],
      ["📴", "off mobile phone"],
      ["📳", "vibration mode"],
      ["🈶", "ideograph have"],
      ["🈚", "ideograph free"],
      ["🈸", "apply ideograph"],
      ["🈺", "open ideograph"],
      ["🈷️", "monthly ideograph"],
      ["✴️", "eight pointed star"],
      ["🆚", "versus vs"],
      ["💮", "white flower"],
      ["🉐", "bargain ideograph"],
      ["㊙️", "secret ideograph"],
      ["㊗️", "congratulations ideograph"],
      ["🈴", "passing ideograph"],
      ["🈵", "full ideograph"],
      ["🈹", "discount ideograph"],
      ["🈲", "prohibited ideograph"],
      ["🅰️", "a button blood type"],
      ["🅱️", "b button blood type"],
      ["🆎", "ab button blood type"],
      ["🆑", "cl button"],
      ["🅾️", "o button blood type"],
      ["🆘", "sos emergency help"],
      ["❌", "cross mark no wrong"],
      ["⭕", "hollow red circle"],
      ["🛑", "stop sign"],
      ["⛔", "no entry"],
      ["📛", "name badge"],
      ["🚫", "prohibited"],
      ["💯", "hundred 100 perfect score"],
      ["💢", "anger symbol"],
      ["♨️", "hot springs"],
      ["🚷", "no pedestrians"],
      ["🚯", "no littering"],
      ["🚳", "no bicycles"],
      ["🚱", "non potable water"],
      ["🔞", "no one under eighteen"],
      ["📵", "no mobile phones"],
      ["🔇", "muted speaker"],
      ["🔕", "bell slash"],
      ["🚭", "no smoking"],
      ["❗", "exclamation mark"],
      ["❕", "white exclamation mark"],
      ["❓", "question mark"],
      ["❔", "white question mark"],
      ["‼️", "double exclamation"],
      ["⁉️", "exclamation question"],
      ["🔅", "dim brightness"],
      ["🔆", "bright brightness"],
      ["〽️", "part alternation mark"],
      ["⚠️", "warning"],
      ["🚸", "children crossing"],
      ["🔱", "trident emblem"],
      ["⚜️", "fleur-de-lis"],
      ["🔰", "beginner japanese"],
      ["♻️", "recycling symbol"],
      ["✅", "check mark green done"],
      ["🈯", "reserved ideograph"],
      ["💹", "chart increasing yen"],
      ["❇️", "sparkle"],
      ["✳️", "eight spoked asterisk"],
      ["❎", "cross mark button no"],
      ["🌐", "globe meridians internet"],
      ["💠", "diamond dot"],
      ["Ⓜ️", "metro circle m"],
      ["🌀", "cyclone spiral"],
      ["💤", "zzz sleep"],
      ["🏧", "atm sign"],
      ["🚾", "water closet wc"],
      ["♿", "wheelchair accessible"],
      ["🅿️", "parking button"],
      ["🛜", "wireless wifi"],
      ["🈳", "vacant ideograph"],
      ["🔣", "input symbols"],
      ["ℹ️", "information source"],
      ["🔤", "abc latin letters"],
      ["🔡", "lowercase latin"],
      ["🔠", "uppercase latin"],
      ["🆖", "ng button"],
      ["🆗", "ok button"],
      ["🆙", "up cool button"],
      ["🆒", "cool button"],
      ["🆕", "new button"],
      ["🆓", "free button"],
      ["0️⃣", "zero key"],
      ["1️⃣", "one key"],
      ["2️⃣", "two key"],
      ["3️⃣", "three key"],
      ["4️⃣", "four key"],
      ["5️⃣", "five key"],
      ["6️⃣", "six key"],
      ["7️⃣", "seven key"],
      ["8️⃣", "eight key"],
      ["9️⃣", "nine key"],
      ["🔟", "keycap ten"],
      ["🔢", "input numbers 123"],
      ["#️⃣", "hash keycap pound"],
      ["*️⃣", "star keycap asterisk"],
      ["⏏️", "eject"],
      ["▶️", "play button"],
      ["⏸️", "pause button"],
      ["⏯️", "play pause button"],
      ["⏹️", "stop button"],
      ["⏺️", "record button"],
      ["⏭️", "next track"],
      ["⏮️", "last track"],
      ["⏩", "fast forward"],
      ["⏪", "rewind"],
      ["⏫", "fast up"],
      ["⏬", "fast down"],
      ["◀️", "reverse button"],
      ["🔼", "upwards triangle button"],
      ["🔽", "downwards triangle button"],
      ["➡️", "right arrow"],
      ["⬅️", "left arrow"],
      ["⬆️", "up arrow"],
      ["⬇️", "down arrow"],
      ["↗️", "up right arrow"],
      ["↘️", "down right arrow"],
      ["↙️", "down left arrow"],
      ["↖️", "up left arrow"],
      ["↕️", "up down arrow"],
      ["↔️", "left right arrow"],
      ["↩️", "left hook reply undo"],
      ["↪️", "right hook"],
      ["⤴️", "right arrow curving up"],
      ["⤵️", "right arrow curving down"],
      ["🔀", "shuffle twisted arrows"],
      ["🔁", "repeat"],
      ["🔂", "repeat single"],
      ["🔄", "counterclockwise arrows refresh"],
      ["🔃", "clockwise arrows"],
      ["🎵", "musical note"],
      ["🎶", "musical notes music"],
      ["➕", "plus add"],
      ["➖", "minus subtract"],
      ["➗", "divide"],
      ["✖️", "multiply"],
      ["🟰", "heavy equals sign"],
      ["♾️", "infinity"],
      ["💲", "heavy dollar sign money"],
      ["💱", "currency exchange"],
      ["™️", "trademark"],
      ["©️", "copyright"],
      ["®️", "registered"],
      ["👁️‍🗨️", "eye in speech bubble"],
      ["🔚", "end arrow"],
      ["🔙", "back arrow"],
      ["🔛", "on arrow"],
      ["🔝", "top arrow"],
      ["🔜", "soon arrow"],
      ["〰️", "wavy dash"],
      ["➰", "curly loop"],
      ["➿", "double curly loop"],
      ["✔️", "check mark done yes"],
      ["☑️", "ballot box check"],
      ["🔘", "radio button"],
      ["🔴", "red circle"],
      ["🟠", "orange circle"],
      ["🟡", "yellow circle"],
      ["🟢", "green circle"],
      ["🔵", "blue circle"],
      ["🟣", "purple circle"],
      ["⚫", "black circle"],
      ["⚪", "white circle"],
      ["🟤", "brown circle"],
      ["🔺", "red triangle up"],
      ["🔻", "red triangle down"],
      ["🔸", "small orange diamond"],
      ["🔹", "small blue diamond"],
      ["🔶", "large orange diamond"],
      ["🔷", "large blue diamond"],
      ["🔳", "white square button"],
      ["🔲", "black square button"],
      ["▪️", "black small square"],
      ["▫️", "white small square"],
      ["◾", "black medium small square"],
      ["◽", "white medium small square"],
      ["◼️", "black medium square"],
      ["◻️", "white medium square"],
      ["⬛", "black large square"],
      ["⬜", "white large square"],
      ["🟥", "red square"],
      ["🟧", "orange square"],
      ["🟨", "yellow square"],
      ["🟩", "green square"],
      ["🟦", "blue square"],
      ["🟪", "purple square"],
      ["🟫", "brown square"],
      ["💎", "gem diamond jewel"],
      ["🔈", "speaker low"],
      ["🔉", "speaker medium volume"],
      ["🔊", "speaker high volume loud"],
      ["📢", "loudspeaker megaphone"],
      ["📣", "cheering megaphone"],
      ["📯", "postal horn"],
      ["🔔", "bell notification"],
      ["🏴", "black flag"],
      ["🏳️", "white flag"],
      ["🏁", "checkered flag finish"],
      ["🚩", "triangular flag red"],
      ["🏳️‍🌈", "rainbow flag pride lgbtq"],
      ["🏳️‍⚧️", "transgender flag"],
      ["🏴‍☠️", "pirate flag"],
    ],
  },
];

/**
 * Flat array of all emojis for quick validation / fallback.
 */
export const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap((cat) =>
  cat.emojis.map(([emoji]) => emoji),
);

/**
 * Default emoji for new profiles (matches AUTH_DEFAULT_EMOJI in AuthContext).
 */
export const DEFAULT_EMOJI = "⚡️";
